# Generated by Django 4.2.4 on 2024-03-22 07:46
from random import sample

from django.db import migrations


def add_barcodes(apps, schema_editor):
    Product = apps.get_model('main_app', 'Product')
    products = Product.objects.all()

    min_barcode = 100_000_000
    max_barcode = 999_999_999
    product_barcodes = sample(range(min_barcode, max_barcode), len(products))

    for product, barcode in zip(products, product_barcodes):
        product.barcode = barcode

    Product.objects.bulk_update(products, ['barcode'])


def remove_barcodes(apps, schema_editor):
    Product = apps.get_model("main_app", "Product")
    products = Product.objects.all()

    # Set the barcode attribute to 0 for each product
    for product in products:
        product.barcode = 0

    # Save the changes to the database
    Product.objects.bulk_update(products, ['barcode'])


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0005_product_barcode'),
    ]

    operations = [
        migrations.RunPython(add_barcodes, remove_barcodes)
    ]
