version: '3.4'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1123QwER
      POSTGRES_USER: postgres
      POSTGRES_DB: python_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgre:/var/lib/postgresql/data
