# Generated by Django 4.2.7 on 2024-04-16 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_picture',
            new_name='profile_url',
        ),
    ]
