# Generated by Django 4.2.7 on 2024-03-26 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_create_company_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companymembers',
            options={'verbose_name_plural': 'Company Members'},
        ),
    ]
