first_number = int(input())
second_number = int(input())
print(f'Before:')
print(f'a = {first_number}')
print(f'b = {second_number}')
print(f'After:')
print(f'a = {second_number}')
print(f'b = {first_number}')