# Generated by Django 4.2.7 on 2024-04-05 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('user_app', '0002_create_user_profile'),
    ]

    operations = [
    ]
