# Generated by Django 4.2.7 on 2024-04-05 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_create_user_profile'),
        ('company', '0002_create_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Company', to='company.company')),
                ('members', models.ManyToManyField(to='user_app.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Company Members',
            },
        ),
    ]
