# Generated by Django 4.2.2 on 2023-06-20 17:59

import GamePlay.base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.FloatField(validators=[GamePlay.base.validators.BetweenTwoNumberValidator(0.1, 5.0)]),
        ),
    ]
