# Generated by Django 4.2.2 on 2023-06-18 19:13

import MyPlantsApp.base.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = []
