# Generated by Django 4.2.2 on 2023-06-18 19:13

import MyPlantsApp.base.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username',models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=20,validators=[MyPlantsApp.base.validators.first_letter_of_string_to_be_capital_validator])),
                ('last_name', models.CharField(max_length=20,validators=[MyPlantsApp.base.validators.first_letter_of_string_to_be_capital_validator])),
                ('profile_picture', models.ImageField(upload_to='profiles')),
            ],
        ),
    ]
