# Generated by Django 4.2.2 on 2023-06-18 19:14

import MyPlantsApp.base.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_create_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('outdoor_plants', 'Outdoor Plants'), ('indoor_plants', 'Indoor Plants')], max_length=14)),
                ('name', models.CharField(max_length=20, validators=[MyPlantsApp.base.validators.only_letter_validator, django.core.validators.MinLengthValidator(2)])),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
