# Generated by Django 4.2.7 on 2023-11-13 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBaseInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=128, null=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product.group')),
            ],
        ),
    ]
