# Generated by Django 4.2.7 on 2024-03-26 14:50

from django.db import migrations


def create_default_group(apps, schema_editor):
    GroupModel = apps.get_model('product', 'Group')

    GroupModel.objects.create(
        name='Стоки',
    )


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0004_create_group'),
    ]

    operations = [
        migrations.RunPython(create_default_group)
    ]
