# Generated by Django 4.2.7 on 2023-11-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productbaseinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAdditionalInfo',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('more_barcodes', models.ManyToManyField(blank=True, to='product.morebarcodes')),
            ],
        ),
    ]
