# Generated by Django 4.2.7 on 2023-11-14 11:50

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productadditionalinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productadditionalinfo',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='productadditionalinfo',
            name='more_barcodes',
        ),
        migrations.AddField(
            model_name='morebarcodes',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.productbaseinformation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productadditionalinfo',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productbaseinformation',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
