# Generated by Django 4.2.7 on 2023-11-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_product_id_productadditionalinfo_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbaseinformation',
            name='barcode',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
