# Generated by Django 4.2.7 on 2023-11-27 21:06

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0007_alter_productbaseinformation_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productadditionalinfo',
            name='picture',
        ),
        migrations.AddField(
            model_name='productbaseinformation',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productbaseinformation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
