# Generated by Django 4.2.7 on 2024-03-27 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_create_default_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[(1, 'Standard'), (2, 'Service'), (3, 'Payment')], default=1, max_length=3)),
                ('vat_group', models.CharField(choices=[(1, 'А (0%)'), (2, 'Б (20%)'), (3, 'В (20%)'), (4, 'Г (9%)')], default=2, max_length=4)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='product.group')),
                ('measure', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.unit')),
            ],
        ),
    ]
