# Generated by Django 4.2.7 on 2023-11-27 21:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_productadditionalinfo_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbaseinformation',
            name='picture',
        ),
        migrations.AddField(
            model_name='productadditionalinfo',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
