# Generated by Django 4.2.7 on 2024-03-27 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_create_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcodes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='product.barcode')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='barcodes', to='product.product')),
            ],
        ),
    ]
