# Generated by Django 4.2.2 on 2023-06-19 18:10

import CarColletion.base.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sports_car', 'Sports Car'), ('pickup', 'Pickup'), ('crossover', 'Crossover'), ('minibus', 'Minibus'), ('other', 'Other')], max_length=10)),
                ('model', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('year', models.PositiveSmallIntegerField(validators=[CarColletion.base.validators.BetweenTwoYearsValidator(1980, 2049)])),
                ('image_url', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
