# Generated by Django 4.2.2 on 2023-06-24 06:20

import Fruitipedia.base.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = []
