# Generated by Django 4.2.2 on 2023-06-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_create_fruit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='nutrition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
